apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-http-gov
spec:
  hosts:
  - www.gov.cn
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: gov
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    route:
    - destination:
        host: www.gov.cn
        port:
          number: 80
      weight: 100
